// AUTO-GENERATED by scripts/build-layers.mjs — do not edit.

export type Layer = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export type Scene = {
  slug: string;
  cast: Layer;
  plate: Layer;
};

export const SCENES = [
  {
    "slug": "first-look",
    "cast": {
      "src": "/layers/first-look-cast.webp",
      "width": 769,
      "height": 1178,
      "blurDataURL": "data:image/webp;base64,UklGRmICAABXRUJQVlA4WAoAAAAQAAAAFwAAJAAAQUxQSOgAAAART6CgbRsWF8bdiYjA85JNB1C1bVvbPGXLbeqiBi5yc5WrG2+/G4Nj+O04tvi/x/t/6TFE9H8CsLObMsVTJVbztzrVpvWg4VSJNdX2RFVrpmSqrZLxqFdJp0YWFJeBZpBZBUayGyttArtW7oCHD2MnByZXxqmH5v/c0AZ8JpYvkTksB/MKS+MeTiAYnthKjKVRW+FN1SiVpH3rTFI+UiWaSrpPVQWaQdK4GerAoyLmmzQvFTsmY5YqeHBFeWX3nk9LLvOky4LUw2hp1Jo5sBskOfgHaC3+79dohjLAmU/gzJei5uEAdrsAVlA4IFQBAACQBwCdASoYACUAPxF0tFMsJiSiqrgMAYAiCWoArlWNY4yB7cAqdr64OTSdsbfzPllSrk9OIMkKiWFj9BYfyi/6NriVkwAA/vQs4yvCbEIIkDhACYyxQrExkPXskh8Xg/EQ4fAHxHmKS/AEABxZPlg0V7Xd1Bi8ljHDJhShS/ZhFG6xIXq396VKtZubAC1HLglAfvlz1si2z8/2RpNwwD/STMALGCoTeeQI9tWR5E8dTZqlHREMZyb3Gp9l2SzLz0goCmr7TA81wir4DfHb3sD3GKvq5tK0AckKCpT2Byl0+z8okuB/ajYfKP0j3OK1AetxPErbhEtA9LvBtIMflKNYTok7SUk8s30DTX/H7rsa3WMFSXImT7FUhiqLz1lxT+UjXZvy5mz8+hrF9XBZkEMCC7uCki97YEhX+BJmFf4zqrfLCnza/lilZSrsR9UdkKtKAAAA"
    },
    "plate": {
      "src": "/layers/first-look-plate.jpg",
      "width": 1536,
      "height": 1024,
      "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACQBACdASoYABAAPxFysFAsJqSisAgBgCIJaACdMoMYAE5gvbnSjLl32nLS6uAA/p+6zdhNoGtvL43zijhPdfb5gztwHi4It7/QfRHG8IrAssS+ca90SA3MeZgCLTfQmXeIY4eAza/lv7887MAlaNeDeD5Qr8nRmtEdycKlNqfFCeY3CSvht0Woq7AenDl6W0MHJz5EEAA="
    }
  },
  {
    "slug": "rooftop",
    "cast": {
      "src": "/layers/rooftop-cast.webp",
      "width": 523,
      "height": 1384,
      "blurDataURL": "data:image/webp;base64,UklGRqoDAABXRUJQVlA4WAoAAAAQAAAAFwAAPwAAQUxQSFIBAAART6CgbRsWl8XbjYhAr/+fbsi1tk2RlK+9w3XJasLO1qEzHCrDoTIcOsOhs3UJR2qmvuut/+9riOj/BGDo6s9MM3aWazudLzR8880Ad+I0047+a0+bfZ8oxzWmmTItMa4Un+F7o4QEd5xkOsD0wJ2rHE8tgHkGzxYnDYDpliFv0skWgO/uKXmT+xLAHV6SXA8FYP4wfs0UWLoXotADWLoj0AHABcUWwJ3/QWgAnP2jtnRwcaNh5L9dRy2ApVd/L6MmuvvoPNoGADN6FUhWEczugmQh4A5JptKUZA/RkKSTvkdWmkaN5KNtKQzZYVwL74RSMIsoFzCNUmlMsof8nWSrPCVZKTskM2WJ7KEH2gELtoO6QcwHVdqc3NZ8F1pt6mZWO7Hfnfbd7XTaU4tQKDsW81ZZ6jCzWkgnTsEi/95rIX13k0hLIX3qIO8w3ymUpc8pYlZQOCAyAgAAkAsAnQEqGABAAD8RerRRLCglIqwaqzGAIglsAJ05QVi+bA5l+faU8/+JAaZn6AHSu/6qvmzxJjZY1mOqm3g+xxfTkX1smE8rg/oBH0hKY7NgZMlHQ95B9VnnSK7t+ULvmkjmBgAA/lXO2KQB12xRFzB9dvubqNFu2MbQM64VavGtss6892kIROfhoUTcL2RhuwQ+q+Ko0xeDWzoGNQ4V1/sS+q6BrHOIltyo+tQmOkJc4YS5nysc+6u48v3plESkeLsW9/K8iNr1HP1UAC6j+pcK++KmcCcW5V7fexMvx+SRpEaRY6HGwqEmC2PvTo92ARiy51wblO6qVPNIDhP1RxCJMkBpEokXV8cGamFXkuNvuzxgtdeVrrlHjgLaBmBHaox3OIx/zoa6zwNYAKZol/PfvxbfBgHNfT0zte5DNzWmtP9j2GBD3jFnOM5IbKY2Mzy/2QVPUWskUBMQxqlNmlD32/KMw7bDHSP8bukUC5ltOVYtilVO3gXN6PqIK6WuPPhlQ005bQ/yhX9ztbTI6rfx83gRHobb1scAOep3Z+tgo2vppY9IvynAp5m71P8B2gTntMVItcnop+yB2K1Yp7jmBYXBlu6oWsTOpainMY0SmY9x3XKJCRiJ/gQQNCmwxCBttDAoVdjbFRJGH6yC8iFOTb9wl/XiCDM2w4Qpht9jhSKlp5L7HVn3Mk25/DF0XlPno/Vuf5SBiVvdHzj5rAUmt6OX5NHzusbDgpGysAAAAA=="
    },
    "plate": {
      "src": "/layers/rooftop-plate.jpg",
      "width": 1536,
      "height": 1024,
      "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBACdASoYABAAPxFysFAsJqSisAgBgCIJbAC2yCPt1GY38+rgfGXihtmIAP7jf40cnnwapg4aQyUXKPLRtXgtLPzGJZLVzxKIsNFTirlhqGl+T+BK4UsloWVeunKITPl4NvldYw9RtCTThUy+TnWIF4qXgoo8NOn+PIlLKN/AAA=="
    }
  },
  {
    "slug": "field",
    "cast": {
      "src": "/layers/field-cast.webp",
      "width": 704,
      "height": 1375,
      "blurDataURL": "data:image/webp;base64,UklGRrgCAABXRUJQVlA4WAoAAAAQAAAAFwAALgAAQUxQSO4AAAART6AgbQMWzsZfRARK+tsCqNq2vU3ejA4Z1eFy4eIiWxcUVxwb4hgqjg1xbIjtfo43//cfQ0T/J2BPvs9eDxOPRL+RlAadM+1X0moi6fFA+uwnu1J6nElK65RKD5W6ywvq2yZwFACx3CsYyVxAaL1DYN3RehzSyKf1uIPIWkDfWsPUyIHauAPawLUEiF2bTt+R7DpDR0E38yod+S/QZg7dAVXg+ujIvQTawLUCCF1HQBO4ciCTz9zj0mu8K42UeDM3tA2XA+tfH0MjaXQ3NdJGd5mR1LryKFVMDc2U+k2MvFJeGp+l8jZwPUbSdywJVlA4IKQBAACwCQCdASoYAC8APxFysFEsJqSiqqwBgCIJbACdOUFVeiS6saLc9VZLz6PMcbHYwJW821pgH6Zh1VU7jLt0mR+ZT8Efy0Tv5h5fm2hfWtNxEG5UxzvLoAD9+6sLStnSTOOcM/78Yg301BrM/vKRtmWA7Sm/Qu9EiCVrja7ool7criVwUnSuBYYON/bfS0leHAIzETamI/LlAePl4OpSW6AYJCzGCgD4xWkhZlujok0KAIaarAdkzeX4EV0E/h3bNOwYjXqwXYY2T6s9y57SB8GqPEZDljS2fZVMgSTQFN9by2+K/4qJaj+m0Zww0NniyNUVrIFYHfUr/aTsCfUqhZeZfrPM8uiqMkPXNMW5DaT18L49TDWqbESmVdxg3Ke4Z+PPVV291u1DqTTdLUsQvOjXiOnt99MyMfk2j9W+XUrNXbeHzrSM2nnKBxa5feDcwMYQi3s1q+1gMHTb9zp7NTfDAgg2jL7hNu+PKJAhVVgZxx8SCT3hE0+4oXM0sPU58j8N/9S53dxTVvXfc//yQf+T4MUuqca/Z9Y7oLbVZcwRLa2wAAA="
    },
    "plate": {
      "src": "/layers/field-plate.jpg",
      "width": 1536,
      "height": 1024,
      "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBACdASoYABAAPxFysFAsJqSisAgBgCIJbACdMoR4OsAA5FVt78lBtvTw/fwAAP7aviIWbKWCzfsSkX2DDytqHiccCjclMV1EDC0IArBfQXZTFHSmdLTScSACc5E/+UTRVg1eQ/kNIxoaGyNAt7D19JGGhWuencUVfqWudwoAAA=="
    }
  },
  {
    "slug": "colour",
    "cast": {
      "src": "/layers/colour-cast.webp",
      "width": 450,
      "height": 1254,
      "blurDataURL": "data:image/webp;base64,UklGRjADAABXRUJQVlA4WAoAAAAQAAAAFwAAQgAAQUxQSCsBAAART6CgbRsWF8bbjYiAan96REC1bdt1sl9JkVeluIcDF9VckHFxjLgAKo4Oz9HhydR79veec883RPR/AqBvX3Mk5+Qg9UFuUgeSuRWEZNuqSHJgLdW5tXdFTxDVz9Ql9RT6ZLAEEMSaARjRXgGYJ2pfBiwTTQasE8yB91QBbClWqf6VsA3s+KR+OASOzYP65gA48WgtgEjzhwsEscayQkW7e9ggiDVb18AxGouKOY5ibHAsg9Cs8dGe026y5XCfYDZfxFQeGnHgNSaaLExOnuzn36oBhLUHd9ZGfbh21kztrYE6WKU6WoU6WbmKRpMBCOKip7JYAhhZTQ6gEmMFfXZLNjIwUF2d6lPLAnZ1LFJ3ZJ5akkVq5ArigbB0RBaeGk6ZeWLXdeGaeW56BgBWUDgg3gEAABAKAJ0BKhgAQwA/EXqyU6wnpCKpuqtpgCIJbA3CZShwfkhQItDPUc9VpgG8wf6pIOzUwTdIMdfcKFc9gba/F+xjrp02s3oEg/CgSYKqXlQOYTluUn185ZIAAP65+RiLCLcSs1OaEUEjS16sTCjbHu0J2rtr4y8eIADbe9I+HPQ8s1EsrkVSALaYwkMFNC35ALNCTudnye/7oc/4oQgQknlQ7BritcPgu+IfetP0qdYM6wpPJUCzruwrzPCPt1MPpns/72iqJl/8FJTEIsIJVcqECNqCUNVJowHZNcKQ2VsRO1JG1AYueUOXxwJ1kTNwPZB8WGumEcqUstZ/d1boTBvATq5YlRtwehQFMXiERk6iwO8y7yL1IWvVpsdi9v4fmKIl8A3NAr5f95GkaVtqCkT+2Zh4bEvV1K8fMsi2KY9vOeV/lirkC849HOQLyD5ujp2x9fXAuxj9rw1Y7d5wb0U4KfRBovVSRI4ep+Zyhk4hPPPWv18GpEkLDbTAXSxTQJb/HPV3ESabl7XO8SycJCH57awjCNePQQPUG2dOKRn7IlgTz0ObLhuoMCxz7HrTujBx99PHrHJeZyu9/tMA436j+r9PUZ5q3erv2I0W55OUyuX3FCaaD/oDmQPzgAA="
    },
    "plate": {
      "src": "/layers/colour-plate.jpg",
      "width": 1536,
      "height": 1024,
      "blurDataURL": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAACQBQCdASoYABAAPxFysFAsJqSisAgBgCIJbACdMoMYNcBhat3YexwBDKCBZqoM+ItY+ZNWEAD+z3H96ekczpe68Ii9t6VMw3WNGrbXcAajFPOtcdF8LQqRWXzG4e8OTfnxhVe5+YVy6JVx2SH+WvfVwJXadQQEZH1jlt6cLEqMQr+BqGsrFG66sGwmHHmfA02k4vymkH7t5Um8K4B25nXOPvfLfU1XwG2Dv5NjWY44vIBzNbW/wjPQAAA="
    }
  }
] as const satisfies readonly Scene[];
